site_name: Adventronics Calendar 
site_description: Adventronics Calendar
site_author: Future Learning Unit (FLU)
repo_name: 'Adventronics Calendar'
repo_url: 'https://github.com/fablabbcn/adventronics/'
copyright: 'Copyleft 2024 FLB - GNU Free Documentation License'

nav:
  - Home:
    - index.md
  - Barduino:
    - barduino.md
  - How to particpate?:
    - howto.md
  - Solutions:
    - Day 1: solutions/01/01.md
    - Day 2: solutions/02/02.md
    - Day 3: solutions/03/03.md
    - Day 4: solutions/04/04.md
    - Day 5: solutions/05/05.md
    - Day 6: solutions/06/06.md
    - Day 7: solutions/07/07.md
    #- Day 8: solutions/08/08.md
    #- Day 9: solutions/09/09.md
    #- Day 10: solutions/10/10.md
    #- Day 11: solutions/11/11.md
    #- Day 12: solutions/12/12.md
    #- Day 13: solutions/13/13.md
    #- Day 14: solutions/14/14.md
    #- Day 15: solutions/15/15.md
    #- Day 16: solutions/16/16.md
    #- Day 17: solutions/17/17.md
    #- Day 18: solutions/18/18.md
    #- Day 19: solutions/19/19.md
    #- Day 20: solutions/20/20.md
    #- Day 21: solutions/21/21.md
    #- Day 22: solutions/22/22.md
    #- Day 23: solutions/23/23.md
    #- Day 24: solutions/24/24.md
  - Solution template:
    - template.md


theme: 
  name: 'material'
  icon:
    annotation: material/plus-circle 
    admonition:
      note: material/party-popper
      tip: material/balloon
      question: material/robot
      warning: material/cookie
      bug: material/candle
      example: material/snowflake
  logo: images/flb.svg
  favicon: images/Barduino4.svg
  features:
    - instant
    - navigation.expand
    - tabs
    - toc.autohide
    - navigation.tabs
  palette:
    scheme: slate
    primary: black
      

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  analytics:
    provider: google
    property: G-WL24PGLVEQ
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
